repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.59
    hooks:
      - id: ty
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --branch=master
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --indent=4
          - --autofix
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.7.0
    hooks:
      - id: eslint
        args: [--config, eslint.config.js]
        files: \.(js|mjs)$
        additional_dependencies:
          - eslint@10.7.0
          - '@eslint/js'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|css|html)$
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v17.14.0
    hooks:
      - id: stylelint
        files: \.(css)$
        additional_dependencies:
          - stylelint@17.14.0
          - stylelint-config-standard
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=tekst
          - --skip="./.*"
          - --quiet-level=2
        exclude_types: [csv, json]
