topic_prefix: weather-dashboard

sensors:
  condition:
    type: condition
    name: Obecne warunki
  air_quality:
    type: text
    name: Jakość powietrza
  forecast:
    type: forecast
    name: Prognoza
  alerts:
    type: alerts
    name: Alerty meteorologiczne
  temperature:
    name: Temperatura
    icon: mdi:thermometer
    color: "#FF6F22"
    round: 1
    unit: °C
  apparent_temperature:
    name: Temperatura odczuwalna
    icon: mdi:thermometer
    color: "#FF6F22"
    round: 1
    unit: °C
  humidity:
    name: Wilgotność
    icon: mdi:humidity_percentage
    color: "#2196F3"
    round: 0
    unit: "%"
  pressure:
    name: Ciśnienie
    icon: mdi:speed
    color: "#009688"
    round: 0
    unit: hPa
  precipitation_probability:
    name: Prawdopodobieństwo opadów
    icon: mdi:umbrella
    color: "#2196F3"
    round: 0
    unit: "%"
  pm1:
    name: Pył zawieszony PM1
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
  pm25:
    name: Pył zawieszony PM2.5
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
  pm10:
    name: Pył zawieszony PM10
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
  water_level:
    name: Poziom wody w Bzurze
    icon: mdi:waves
    color: "#2196F3"
    round: 0
    unit: cm
