topic_prefix: weather-dashboard

sensors:
  temperature:
    name: Temperature
    icon: mdi:thermometer
    color: "#FF6F22"
  humidity:
    name: Humidity
    icon: mdi:humidity_percentage
    color: "#2196F3"
  pressure:
    name: Pressure
    icon: mdi:gauge
    color: "#009688"
  pm10:
    name: PM10
    icon: mdi:molecule
    color: "#607D8B"
  pm25:
    name: PM25
    icon: mdi:molecule
    color: "#607D8B"
