topic_prefix: weather-dashboard

sensors:
  condition:
    type: condition
    name: Obecne warunki
    color: "#FFB300"
  air_quality:
    type: text
    name: Jakość powietrza
    color: "#607D8B"
  temperature:
    name: Temperatura
    icon: mdi:thermometer
    color: "#FF6F22"
    round: 1
    unit: °C
  apparent_temperature:
    name: Temperatura odczuwalna
    icon: mdi:thermometer
    color: "#FF6F22"
    round: 1
    unit: °C
  humidity:
    name: Wilgotność
    icon: mdi:humidity_percentage
    color: "#2196F3"
    round: 0
    unit: "%"
  pressure:
    name: Ciśnienie
    icon: mdi:speed
    color: "#009688"
    round: 0
    unit: hPa
  pm1:
    name: Pył zawieszony PM1
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
  pm10:
    name: Pył zawieszony PM10
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
  pm25:
    name: Pył zawieszony PM25
    icon: mdi:air
    color: "#607D8B"
    round: 0
    unit: µg/m³
